baseurl = "https://voigt.github.io/"
title = "Voigt Site"
languageCode = "en-us"
theme = "slim"

[Params]
  Author = "Christoph Voigt"
  Subtitle: "Your site's subtitle/tagline"
  GithubID: "voigt"
  TwitterID: "vogti"