baseurl = "https://voigt.github.io/"
title = "Notes on #Golang"
languageCode = "en-us"
theme = "slim"

[params]
  Author = "Christoph Voigt"
#  Subtitle = "Notes on Golang"
  GithubID = "voigt"
  TwitterID = "vogti"
  AnalyticsID: UA-44298521-2
  DisqusShortname: voigt-github-io

[[menu.main]]
    name = "about"
    weight = -110
    identifier = "about"
    url = "/about/"