baseurl = "https://voigt.github.io/"
title = "Voigt Site"
languageCode = "en-us"
theme = "slim"

[params]
  Author = "Christoph Voigt"
  Subtitle = "Your site's subtitle/tagline"
  GithubID = "voigt"
  TwitterID = "vogti"

[[menu.main]]
    name = "about"
    weight = -110
    identifier = "about"
    url = "/about/"