spin_manifest_version = 2

[application]
authors = ["Christoph Voigt <voigt.christoph@gmail.com>"]
description = "My Personal Website"
name = "christophvoigt-website"
version = "0.1.0"

# [[trigger.http]]
# route = "/api/v1/..."
# component = "api"
#
# [component.api]
# source = "api/target/wasm32-wasip2/release/api.wasm"
# allowed_outbound_hosts = []
# key_value_stores = ["default"]
#
# [component.api.build]
# command = "cargo build --target wasm32-wasip2 --release"
# watch = ["src/**/*.rs", "Cargo.toml"]
# workdir = "api"

[[trigger.http]]
route = "/..."
component = "hugo"

[component.hugo]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "static", destination = "/" }]

[component.hugo.build]
command = "HUGO_ENVIRONMENT='production' HUGO_ENV='production' hugo -s ../ -d ./spin/static/ --minify --baseURL 'https://christophvoigt.com/'"
