env:
  global:
    - secure: "rCvkWyIpMNeSuQ6ZMCaopIMDKO6Wz7WdSKZMxMp9X2IVE5Fgi5uuoKEcCxECOnJwAo9hcDRcFQCxICYqJ2aq8jg6QraCY8u5JhsxClz790+s5UJNo68N8hZLbV98SxS3aN+or8HMrVFmbVCOvDdPIRMYsIWc5cHKW9a2pJApjwmmi/DWhMnw8QRfsEO/lyEFxjBPKjTuNIDgQngZ7QFR6FHZXvzgRyNWm2TOTrIlmp9iEb7AL/fC/ZVby1lExqm1qy/OjwygjmA63JFJ/1yLDrYoXy4uNaSfWGJ+V2+TwMIx8M1mIaKPBacxQZJMPq74SBJySlwd7k/P7A7AkIENC1cg+BJkwucyW+QzPD7UXgqrTfJFtS7025R4dZF0pvcv683wk6oyH1jfNSJ4xJrEDK9ZBBaW4WCt1YT5qMvYa8I9yIQffBjoy9BkI/XqNno2AEe4Bs3lbV+v8wwe2cZOypYcz9oHj399mw2GrUwcjh/pR9fUELGyCn9X3ym8pCnXpgR2sO6OgagL0WNSRJlvg5aHNYq3mGNLAsUeOmlIGsYCsu8u7KrFGh70WOrURfCHWRuYMPKoSuW6UCLEIcjY97x+hwjuO59ctxYLJ/IIehGCIu+3DmCiBtaRx7zAmkMv8Vnqi7v2o6NvMmBNG+hYym3MTnLtpxXGIH+A0FBelM4="
    - GIT_DEPLOY_DIR=public # this is the default output dir of Hugo
    - GIT_DEPLOY_BRANCH=master # this is the target branch, replace by gh-pages for Project Pages
    - GIT_DEPLOY_USERNAME="Travis CI" # dummy name
    - GIT_DEPLOY_EMAIL=voigt.christoph@gmail.com # replace by your email
branches:
  only:
    - sources # replace by master for Project Pages

install:
  - rm -rf public || exit 0 # cleanup previous run
script:
  - binaries/hugo # generate!
after_success:
  - cp .travis.yml public # all branches need this file
  - bash deploy.sh # run the deploy script
